from crane_auth.exceptions import SystemException


class AutharizationError(SystemException): ...
