from crane_users.exceptions import SystemException


class AutharizationError(SystemException): ...
